print("====================================================")
print("                Advanced Operations                 ")
print("====================================================")
print("  Please select the number of the operation needed  ")
print("____________________________________________________")
print(" ")
print("                  1.                      ")
print("                 2.                     ")
print("               3.                     ")
print("                  4.                     ")
print("____________________________________________________")